/**
 * Trigger substrings for profile dietary/cultural chip labels (must match
 * DIETARY_CHIPS / CULTURAL_CHIPS `label` in the frontend setup form).
 * Matching uses normalizeFoodText-style lowercase alphanumerics + spaces on both sides.
 */
export const DIETARY_CULTURAL_CONSTRAINT_KEYWORDS: Record<string, readonly string[]> = {
  Vegetarian: [
    "chicken",
    "beef",
    "pork",
    "lamb",
    "veal",
    "turkey",
    "duck",
    "goose",
    "bacon",
    "ham",
    "prosciutto",
    "salami",
    "pepperoni",
    "chorizo",
    "sausage",
    "fish",
    "salmon",
    "tuna",
    "cod",
    "shrimp",
    "prawn",
    "crab",
    "lobster",
    "mussel",
    "clam",
    "oyster",
    "squid",
    "octopus",
    "anchovy",
    "sardine",
    "seafood",
    "meat",
    "steak",
    "ribs",
    "ground beef",
    "oxtail",
    "liver",
    "kidney",
    "bone broth",
    "chicken stock",
    "beef stock",
    "fish sauce",
    "worcestershire",
    "gelatin",
    "lard",
    "suet",
  ],
  Vegan: [
    "chicken",
    "beef",
    "pork",
    "lamb",
    "turkey",
    "duck",
    "bacon",
    "ham",
    "fish",
    "salmon",
    "tuna",
    "shrimp",
    "egg",
    "eggs",
    "milk",
    "cream",
    "butter",
    "cheese",
    "yogurt",
    "honey",
    "gelatin",
    "whey",
    "casein",
    "mayonnaise",
    "lard",
  ],
  "Gluten-Free": [
    "wheat",
    "flour",
    "bread",
    "pasta",
    "couscous",
    "bulgur",
    "barley",
    "rye",
    "semolina",
    "spelt",
    "farro",
    "malt",
    "soy sauce",
    "beer",
    "breadcrumbs",
    "croissant",
    "panko",
  ],
  "Dairy-Free": [
    "milk",
    "cream",
    "butter",
    "cheese",
    "yogurt",
    "ghee",
    "whey",
    "casein",
    "parmesan",
    "mozzarella",
    "cheddar",
    "ricotta",
    "mascarpone",
    "heavy cream",
    "sour cream",
    "creme fraiche",
    "condensed milk",
    "evaporated milk",
  ],
  "No Beef": ["beef", "steak", "brisket", "ribeye", "sirloin", "ground beef", "oxtail", "veal", "bolognese"],
  "Nut Free": [
    "almond",
    "cashew",
    "walnut",
    "pecan",
    "pistachio",
    "hazelnut",
    "macadamia",
    "peanut",
    "groundnut",
    "marzipan",
    "praline",
    "pesto",
  ],
  "Shellfish-Free": [
    "shrimp",
    "prawn",
    "crab",
    "lobster",
    "crayfish",
    "mussel",
    "clam",
    "oyster",
    "scallop",
    "shellfish",
    "squid",
    "octopus",
  ],
  "No Pork": [
    "pork",
    "bacon",
    "ham",
    "prosciutto",
    "pancetta",
    "guanciale",
    "lard",
    "sausage",
    "chorizo",
    "salami",
    "pepperoni",
    "trotter",
    "ribs",
  ],
  Halal: [
    "pork",
    "bacon",
    "ham",
    "lard",
    "wine",
    "brandy",
    "rum",
    "beer",
    "vodka",
    "whiskey",
    "sherry",
    "liqueur",
    "vanilla extract",
  ],
  Kosher: [
    "pork",
    "bacon",
    "ham",
    "shellfish",
    "shrimp",
    "crab",
    "lobster",
    "clam",
    "oyster",
    "mussel",
    "scallop",
    "rabbit",
    "rock lobster",
  ],
};
