export const TEXTURE_VALUES = [
  "Soft",
  "Smooth",
  "Crunchy",
  "Crispy",
  "Chewy",
  "Slimy",
  "Mushy",
  "Lumpy",
  "Sticky",
  "Grainy",
  "Rubbery",
  "Flaky",
] as const;

export type TextureValue = (typeof TEXTURE_VALUES)[number];

export const INGREDIENT_TEXTURES: Record<string, readonly TextureValue[]> = {
  "Ackee": ["Soft"],
  "All purpose flour": ["Grainy"],
  "All-purpose Seasoning": ["Grainy"],
  "Allspice": ["Grainy"],
  "Allspice Berries": ["Grainy"],
  "Almond Essence": ["Smooth"],
  "Almond Extract": ["Smooth"],
  "Almond Flour": ["Grainy"],
  "Almond Milk": ["Smooth"],
  "Almond Paste": ["Smooth", "Sticky"],
  "Almonds": ["Crunchy"],
  "Ancho Chillies": ["Chewy"],
  "Anchovy Fillet": ["Chewy"],
  "Apple Cider Vinegar": ["Smooth"],
  "Apples": ["Crunchy"],
  "Appleton rum": ["Smooth"],
  "Apricot": ["Soft"],
  "Apricot Jam": ["Smooth", "Sticky"],
  "Arabic Rice": ["Grainy"],
  "Asparagus": ["Crunchy"],
  "Aubergine": ["Soft"],
  "Avacado Hass Pulp": ["Smooth"],
  "Avocado": ["Soft", "Smooth"],
  "Baby Aubergine": ["Soft"],
  "Baby Lettuce Leaves": ["Crunchy"],
  "Baby New Potatoes": ["Soft"],
  "Baby Pak Koi": ["Crunchy"],
  "Baby Plum Tomatoes": ["Soft"],
  "Baby Squid": ["Rubbery"],
  "Bacon": ["Chewy"],
  "Bacon lardon": ["Chewy"],
  "Baguette": ["Soft", "Crunchy"],
  "Baked Beans": ["Soft"],
  "Baking Powder": ["Grainy"],
  "Balsamic Vinegar": ["Smooth"],
  "Bamboo Shoot": ["Crunchy"],
  "Banana": ["Soft", "Smooth"],
  "Barbeque Sauce": ["Smooth", "Sticky"],
  "barramundi": ["Flaky"],
  "Basil": ["Soft"],
  "Basil Leaves": ["Soft"],
  "Basmati Rice": ["Grainy"],
  "Bay Leaf": ["Soft"],
  "Bay Leaves": ["Soft"],
  "Bean Sprouts": ["Crunchy"],
  "Beef": ["Chewy"],
  "Beef Brisket": ["Chewy"],
  "Beef Cutlet": ["Chewy"],
  "Beef Fillet": ["Chewy"],
  "Beef Flank Steak": ["Chewy"],
  "Beef Gravy": ["Smooth"],
  "Beef Kidney": ["Chewy"],
  "Beef Shin": ["Chewy"],
  "Beef Stock": ["Smooth"],
  "Beef Stock Concentrate": ["Smooth"],
  "Beef Stock Cubes": ["Grainy"],
  "Beef tomatoes": ["Soft"],
  "Beer": ["Smooth"],
  "Beetroot": ["Crunchy"],
  "Bicarbonate Of Soda": ["Grainy"],
  "Birds-eye Chillies": ["Crunchy"],
  "Biryani Masala": ["Grainy"],
  "Black Beans": ["Soft"],
  "Black Cardamom Pods": ["Grainy"],
  "Black Olives": ["Chewy"],
  "Black Pepper": ["Grainy"],
  "Black Pudding": ["Soft"],
  "Black Treacle": ["Smooth", "Sticky"],
  "Blackberries": ["Soft"],
  "Blackcurrant Jam": ["Smooth", "Sticky"],
  "Blue Food Colouring": ["Smooth"],
  "Blueberries": ["Soft"],
  "Boiling Water": ["Smooth"],
  "Bok Choi": ["Crunchy"],
  "Borlotti Beans": ["Soft"],
  "Bouillon Cubes": ["Grainy"],
  "Bouquet Garni": ["Soft"],
  "Bowtie Pasta": ["Chewy"],
  "Braeburn Apples": ["Crunchy"],
  "Bramley Apples": ["Crunchy"],
  "Brandy": ["Smooth"],
  "Bread": ["Soft"],
  "Bread Flour": ["Grainy"],
  "Bread Rolls": ["Soft"],
  "Breadcrumbs": ["Grainy"],
  "Brie": ["Soft", "Smooth"],
  "Broad Beans": ["Soft"],
  "Broccoli": ["Crunchy"],
  "Brown Lentils": ["Grainy"],
  "Brown Rice": ["Grainy"],
  "Brown Rice Noodle": ["Chewy"],
  "Brown Sugar": ["Grainy"],
  "Brussels Sprouts": ["Crunchy"],
  "Bryndza cheese": ["Soft", "Smooth"],
  "Buckwheat": ["Grainy"],
  "Buckwheat Flour": ["Grainy"],
  "Bulgur Wheat": ["Grainy"],
  "Bun": ["Soft"],
  "Buns": ["Soft"],
  "Butter": ["Soft", "Smooth"],
  "Butter Beans": ["Soft"],
  "Buttermilk": ["Smooth"],
  "Butternut Squash": ["Soft"],
  "Cabbage": ["Crunchy"],
  "Cabbage Leaves": ["Crunchy"],
  "Cacao": ["Grainy"],
  "Cajun": ["Grainy"],
  "Callaloo": ["Soft"],
  "Can of chickpeas": ["Soft"],
  "Candied Peel": ["Chewy"],
  "Canned Tomatoes": ["Soft", "Smooth"],
  "Cannellini Beans": ["Soft"],
  "Canola Oil": ["Smooth"],
  "Capers": ["Chewy"],
  "Caramel": ["Smooth", "Sticky"],
  "Caramel Sauce": ["Smooth", "Sticky"],
  "Caramelized Sugar Sauce": ["Smooth", "Sticky"],
  "Caraway Seed": ["Crunchy", "Grainy"],
  "Cardamom": ["Grainy"],
  "Carrots": ["Crunchy"],
  "Casabe": ["Crunchy"],
  "Cashew Nuts": ["Crunchy"],
  "Cashews": ["Crunchy"],
  "Cassaba": ["Crunchy"],
  "Caster Sugar": ["Grainy"],
  "Cayenne Pepper": ["Grainy"],
  "Celeriac": ["Crunchy"],
  "Celery": ["Crunchy"],
  "Celery Salt": ["Grainy"],
  "Challots": ["Crunchy"],
  "Charlotte Potatoes": ["Soft"],
  "Cheddar Cheese": ["Chewy"],
  "Cheese": ["Soft"],
  "Cheese Curds": ["Lumpy", "Soft"],
  "Cheese Slices": ["Soft"],
  "Cherry": ["Soft"],
  "Cherry Tomatoes": ["Soft"],
  "Chestnut Mushroom": ["Soft"],
  "Chestnuts": ["Chewy"],
  "Chicken": ["Chewy"],
  "Chicken Bouillon Powder": ["Grainy"],
  "Chicken Breast": ["Chewy"],
  "Chicken Breasts": ["Chewy"],
  "Chicken drumsticks": ["Chewy"],
  "Chicken Legs": ["Chewy"],
  "Chicken Liver": ["Soft"],
  "Chicken Stock": ["Smooth"],
  "Chicken Stock Concentrate": ["Smooth"],
  "Chicken Stock Cube": ["Grainy"],
  "Chicken Thighs": ["Chewy"],
  "Chicken Wings": ["Chewy"],
  "Chickpea Flour": ["Grainy"],
  "Chickpeas": ["Soft"],
  "Chili Powder": ["Grainy"],
  "Chilled Butter": ["Soft", "Smooth"],
  "Chilli": ["Crunchy"],
  "Chilli Bean Paste": ["Smooth"],
  "Chilli Flakes": ["Grainy"],
  "Chilli Powder": ["Grainy"],
  "Chilli Sauce": ["Smooth", "Sticky"],
  "Chimichurri sauce": ["Smooth"],
  "Chinese Broccoli": ["Crunchy"],
  "Chinese Cabbage": ["Crunchy"],
  "Chinese five spice powder": ["Grainy"],
  "Chinese Leaf": ["Crunchy"],
  "Chinese Long Beans": ["Crunchy"],
  "Chinese Sesame Sauce": ["Smooth"],
  "Chives": ["Soft"],
  "Chocolate Chips": ["Crunchy"],
  "Chopped Chive": ["Soft"],
  "Chopped Onion": ["Crunchy"],
  "Chopped Parsley": ["Soft"],
  "Chopped Tomatoes": ["Soft", "Smooth"],
  "Chorizo": ["Chewy"],
  "Christmas Pudding": ["Soft", "Lumpy"],
  "Chuck Roast": ["Chewy"],
  "Ciabatta": ["Soft"],
  "Cider": ["Smooth"],
  "Cider Vinegar": ["Smooth"],
  "Cilantro": ["Soft"],
  "Cilantro Leaves": ["Soft"],
  "Cinnamon": ["Grainy"],
  "Cinnamon Stick": ["Chewy"],
  "Clams": ["Chewy"],
  "Clear Honey": ["Smooth", "Sticky"],
  "Clotted Cream": ["Smooth"],
  "Cloves": ["Grainy"],
  "Coco Sugar": ["Grainy"],
  "Cocoa": ["Grainy"],
  "Cocoa Powder": ["Grainy"],
  "Coconut Cream": ["Smooth"],
  "Coconut Flakes": ["Flaky", "Chewy"],
  "Coconut Milk": ["Smooth"],
  "Cod": ["Flaky"],
  "Colby Jack Cheese": ["Soft"],
  "Cold Water": ["Smooth"],
  "Condensed Milk": ["Smooth", "Sticky"],
  "Cooked Beetroot": ["Soft"],
  "Cooked Chestnut": ["Soft"],
  "Cooking wine": ["Smooth"],
  "Coriander": ["Grainy"],
  "Coriander Leaves": ["Soft"],
  "Coriander Seeds": ["Crunchy", "Grainy"],
  "Corn Arepa Filled With Mozarella Cheese": ["Soft"],
  "Corn Flour": ["Grainy"],
  "Corn Tortillas": ["Chewy"],
  "Corned Beef": ["Chewy"],
  "Cornmeal": ["Grainy"],
  "Cornstarch": ["Grainy"],
  "Courgettes": ["Soft"],
  "Couscous": ["Grainy"],
  "Cranberry": ["Chewy"],
  "Cream": ["Smooth"],
  "Cream Cheese": ["Smooth", "Soft"],
  "Cream Of Tartar": ["Grainy"],
  "Creamed Corn": ["Smooth", "Lumpy"],
  "Creme Fraiche": ["Smooth"],
  "Crusty Bread": ["Soft", "Crunchy"],
  "Cubed Feta Cheese": ["Soft", "Lumpy"],
  "Cucumber": ["Crunchy"],
  "Cumin": ["Grainy"],
  "Cumin Seeds": ["Crunchy", "Grainy"],
  "Currants": ["Chewy"],
  "Curry Powder": ["Grainy"],
  "Custard": ["Smooth"],
  "Custard Powder": ["Grainy"],
  "Dark Brown Soft Sugar": ["Grainy"],
  "Dark Brown Sugar": ["Grainy"],
  "Dark Chocolate": ["Crunchy"],
  "Dark Chocolate Chips": ["Crunchy"],
  "Dark Rum": ["Smooth"],
  "Dark Soft Brown Sugar": ["Grainy"],
  "Dark Soy Sauce": ["Smooth"],
  "Demerara Sugar": ["Grainy"],
  "Desiccated Coconut": ["Grainy"],
  "Diced Tomatoes": ["Soft", "Lumpy"],
  "Digestive Biscuits": ["Crunchy"],
  "Dijon Mustard": ["Smooth"],
  "Dill": ["Soft"],
  "Dill Pickles": ["Crunchy"],
  "Doner Meat": ["Chewy"],
  "Doubanjiang": ["Smooth", "Lumpy"],
  "Double Cream": ["Smooth"],
  "Dried Apricots": ["Chewy"],
  "Dried Cherries": ["Chewy"],
  "Dried Chillies": ["Chewy"],
  "Dried cranberries": ["Chewy"],
  "Dried Fruit": ["Chewy"],
  "Dried Leaves Of Summer Savoury": ["Grainy"],
  "Dried Mint": ["Grainy"],
  "Dried Oregano": ["Grainy"],
  "Dried Red Chillies": ["Chewy"],
  "Dried Shrimp": ["Chewy"],
  "Dried white beans": ["Grainy"],
  "Dried white corn": ["Grainy"],
  "Dried White Navy Beans": ["Grainy"],
  "Dry sherry": ["Smooth"],
  "Dry White Wine": ["Smooth"],
  "Duck": ["Chewy"],
  "Duck Fat": ["Soft", "Smooth"],
  "Duck Legs": ["Chewy"],
  "Duck Sauce": ["Smooth", "Sticky"],
  "Dulce de leche": ["Smooth", "Sticky"],
  "Dutch Stroop": ["Smooth", "Sticky"],
  "Egg": ["Soft"],
  "Egg Noodles": ["Chewy"],
  "Egg Plants": ["Soft"],
  "Egg Roll Wrappers": ["Chewy"],
  "Egg Rolls": ["Crispy", "Crunchy"],
  "Egg Wash": ["Smooth"],
  "Egg White": ["Smooth"],
  "Egg Yolks": ["Smooth"],
  "Eggs": ["Soft"],
  "Emmentaler Cheese": ["Chewy"],
  "Enchilada Sauce": ["Smooth"],
  "English Muffins": ["Soft"],
  "English Mustard": ["Smooth"],
  "Extra Virgin Olive Oil": ["Smooth"],
  "Fajita Seasoning": ["Grainy"],
  "Falafel": ["Crunchy"],
  "Farfalle": ["Chewy"],
  "Fast action yeast": ["Grainy"],
  "Feather blade beef": ["Chewy"],
  "Fennel": ["Crunchy"],
  "Fennel Bulb": ["Crunchy"],
  "Fennel Seeds": ["Crunchy", "Grainy"],
  "Fenugreek": ["Grainy"],
  "Fermented Black Beans": ["Soft"],
  "Feta": ["Soft", "Lumpy"],
  "Fettuccine": ["Chewy"],
  "Fideo": ["Chewy"],
  "Figs": ["Soft"],
  "Fillet Of Steak": ["Chewy"],
  "Filo Pastry": ["Flaky"],
  "Fine Yellow Cornmeal": ["Grainy"],
  "Fish fillet": ["Flaky"],
  "Fish Sauce": ["Smooth"],
  "Fish Seasoning": ["Grainy"],
  "Fish Stock": ["Smooth"],
  "Five Spice Powder": ["Grainy"],
  "Flaked Almonds": ["Crunchy"],
  "Flat Rice Noodles": ["Chewy"],
  "Flax Eggs": ["Slimy"],
  "Flour": ["Grainy"],
  "Flour Tortilla": ["Chewy"],
  "Floury Potatoes": ["Soft"],
  "Free-range Egg, Beaten": ["Smooth"],
  "Free-range Eggs, Beaten": ["Smooth"],
  "Freekeh": ["Grainy"],
  "French Lentils": ["Grainy"],
  "Fresh Basil": ["Soft"],
  "Fresh Thyme": ["Soft"],
  "Freshly Chopped Parsley": ["Soft"],
  "Fried Ripe Bananas": ["Soft"],
  "Fries": ["Crispy"],
  "Fromage Frais": ["Smooth"],
  "Frozen Mixed Berries": ["Soft"],
  "Frozen Peas": ["Soft"],
  "Frozen Seafood mix": ["Chewy"],
  "Fruit Mix": ["Soft", "Lumpy"],
  "Full fat sour cream": ["Smooth"],
  "Full Fat Yogurt": ["Smooth"],
  "Galangal": ["Crunchy"],
  "Galangal Paste": ["Smooth"],
  "Garam Masala": ["Grainy"],
  "Garlic": ["Crunchy"],
  "Garlic Bulb": ["Crunchy"],
  "Garlic Clove": ["Crunchy"],
  "Garlic Granules": ["Grainy"],
  "Garlic Powder": ["Grainy"],
  "Garlic Sauce": ["Smooth"],
  "Gelatine Leafs": ["Chewy"],
  "German Sausages": ["Chewy"],
  "Ghee": ["Soft", "Smooth"],
  "Gherkin Relish": ["Lumpy", "Sticky"],
  "Ginger": ["Crunchy"],
  "Ginger Cordial": ["Smooth"],
  "Ginger Garlic Paste": ["Smooth"],
  "Ginger Paste": ["Smooth"],
  "Glace Cherry": ["Chewy", "Sticky"],
  "Goat Meat": ["Chewy"],
  "Goats Cheese": ["Soft"],
  "Gochujang": ["Smooth", "Sticky"],
  "Golden Caster Sugar": ["Grainy"],
  "Golden Syrup": ["Smooth", "Sticky"],
  "Goose Fat": ["Soft", "Smooth"],
  "Gouda Cheese": ["Chewy"],
  "Graham Cracker Crumbs": ["Grainy"],
  "Grand Marnier": ["Smooth"],
  "Granulated Sugar": ["Grainy"],
  "Grape leaves": ["Chewy"],
  "Grape Nut Cereal": ["Crunchy", "Grainy"],
  "Grape Tomatoes": ["Soft"],
  "Greek Yogurt": ["Smooth"],
  "Green Beans": ["Crunchy"],
  "Green Cardamom Pods": ["Grainy"],
  "Green Chilli": ["Crunchy"],
  "Green Olives": ["Chewy"],
  "Green Pepper": ["Crunchy"],
  "Green Red Lentils": ["Grainy"],
  "Green Salsa": ["Smooth", "Lumpy"],
  "Ground Allspice": ["Grainy"],
  "Ground Almonds": ["Grainy"],
  "Ground Annatto": ["Grainy"],
  "Ground Beef": ["Chewy"],
  "Ground Cardomom": ["Grainy"],
  "Ground Cinnamon": ["Grainy"],
  "Ground Clove": ["Grainy"],
  "Ground Coriander": ["Grainy"],
  "Ground Cumin": ["Grainy"],
  "Ground Ginger": ["Grainy"],
  "Ground Nut Oil": ["Smooth"],
  "Ground Nutmeg": ["Grainy"],
  "Ground Oats": ["Grainy"],
  "Ground Pistachios": ["Grainy"],
  "Ground Poppy seeds": ["Grainy"],
  "Ground Pork": ["Chewy"],
  "Ground Sugar": ["Grainy"],
  "Gruyère": ["Chewy"],
  "Haddock": ["Flaky"],
  "Hail": ["Crunchy"],
  "Hake": ["Flaky"],
  "Ham": ["Chewy"],
  "Hard Taco Shells": ["Crunchy"],
  "Haricot Beans": ["Soft"],
  "Harissa Spice": ["Grainy"],
  "Hazlenuts": ["Crunchy"],
  "Heavy Cream": ["Smooth"],
  "Herring": ["Flaky"],
  "High Heat Cooking Oil": ["Smooth"],
  "Hind Shank": ["Chewy"],
  "Hispi (sweetheart) Cabbage": ["Crunchy"],
  "Hoisin Sauce": ["Smooth", "Sticky"],
  "Honey": ["Smooth", "Sticky"],
  "Horseradish": ["Grainy"],
  "Hot Beef Stock": ["Smooth"],
  "Hot Chilli Powder": ["Grainy"],
  "Hot Smoked Flaked Salmon": ["Flaky"],
  "Hot smoked paprika": ["Grainy"],
  "Hotsauce": ["Smooth"],
  "Hummus": ["Smooth"],
  "Ice Cream": ["Smooth"],
  "Iceberg Lettuce": ["Crunchy"],
  "Icing Sugar": ["Grainy"],
  "Instant Yeast": ["Grainy"],
  "Italian Fennel Sausages": ["Chewy"],
  "Italian Seasoning": ["Grainy"],
  "Jalapeno": ["Crunchy"],
  "Jam": ["Smooth", "Sticky"],
  "Jamaican Curry Powder": ["Grainy"],
  "jamón ibérico": ["Chewy"],
  "Jasmine Rice": ["Grainy"],
  "Jerk": ["Grainy"],
  "Jersey Royal Potatoes": ["Soft"],
  "Jerusalem Artichokes": ["Crunchy"],
  "Jumbo Shrimp": ["Chewy"],
  "Juniper Berries": ["Grainy"],
  "Kabanos Sausages": ["Chewy"],
  "Kabse Spice": ["Grainy"],
  "Kale": ["Chewy"],
  "Khus Khus": ["Grainy"],
  "Kidney Beans": ["Soft"],
  "Kielbasa": ["Chewy"],
  "King Prawns": ["Chewy"],
  "Knafeh": ["Chewy"],
  "Kosher Salt": ["Grainy"],
  "Lamb": ["Chewy"],
  "Lamb Kidney": ["Chewy"],
  "Lamb Leg": ["Chewy"],
  "Lamb Loin Chops": ["Chewy"],
  "Lamb Mince": ["Chewy"],
  "Lamb Shanks": ["Chewy"],
  "Lamb Shoulder": ["Chewy"],
  "Lamb Stock": ["Smooth"],
  "Lard": ["Soft", "Smooth"],
  "Lasagne Sheets": ["Chewy"],
  "Lean Minced Beef": ["Chewy"],
  "Lean Minced Steak": ["Chewy"],
  "Leek": ["Crunchy"],
  "Lemon": ["Soft"],
  "Lemon Juice": ["Smooth"],
  "Lemon Zest": ["Grainy"],
  "Lemongrass": ["Chewy"],
  "Lemongrass Stalks": ["Chewy"],
  "Lemons": ["Soft"],
  "Lentils": ["Grainy"],
  "Lettuce": ["Crunchy"],
  "Light Brown Soft Sugar": ["Grainy"],
  "Light Rum": ["Smooth"],
  "Lime": ["Soft"],
  "Lime juice": ["Smooth"],
  "Lime Leaves": ["Chewy"],
  "Linguine Pasta": ["Chewy"],
  "Liquid Cheese": ["Smooth"],
  "Little Gem Lettuce": ["Crunchy"],
  "Macaroni": ["Chewy"],
  "Mackerel": ["Flaky"],
  "Madras Paste": ["Smooth"],
  "makrut lime leaves": ["Chewy"],
  "Malai": ["Smooth"],
  "Malt Vinegar": ["Smooth"],
  "manchego": ["Chewy"],
  "Maple Syrup": ["Smooth", "Sticky"],
  "Marinated Tofu": ["Soft"],
  "Marjoram": ["Soft"],
  "Mars Bar": ["Chewy", "Sticky"],
  "Marzipan": ["Smooth", "Sticky"],
  "Mascarpone": ["Smooth"],
  "Massaman Curry Paste": ["Smooth"],
  "Mature Cheddar": ["Chewy"],
  "Mayonnaise": ["Smooth"],
  "Medjool Dates": ["Chewy", "Sticky"],
  "Melted Butter": ["Smooth"],
  "Meringue Nests": ["Crispy"],
  "Milk": ["Smooth"],
  "Milk Chocolate": ["Crunchy"],
  "Minced Beef": ["Chewy"],
  "Minced Garlic": ["Grainy"],
  "Minced Pork": ["Chewy"],
  "Mincemeat": ["Lumpy", "Sticky"],
  "Miniature Marshmallows": ["Chewy"],
  "Mint": ["Soft"],
  "Mirin": ["Smooth"],
  "Mixed Beef Cuts": ["Chewy"],
  "Mixed Grain": ["Grainy"],
  "Mixed Peel": ["Chewy"],
  "Mixed peppers": ["Crunchy"],
  "Mixed Spice": ["Grainy"],
  "Mixture Powder": ["Grainy"],
  "Molasses": ["Smooth", "Sticky"],
  "Monkfish": ["Chewy"],
  "Monterey Jack Cheese": ["Soft"],
  "Morcilla": ["Soft"],
  "Mozzarella": ["Chewy"],
  "Mozzarella Balls": ["Chewy"],
  "Muffins": ["Soft"],
  "Mulukhiyah": ["Slimy"],
  "Mung Bean Sprouts": ["Crunchy"],
  "Muscovado Sugar": ["Grainy"],
  "Mushrooms": ["Soft"],
  "Mussels": ["Chewy"],
  "Mustard": ["Smooth"],
  "Mustard Powder": ["Grainy"],
  "Mustard Seeds": ["Crunchy", "Grainy"],
  "Naan Bread": ["Soft", "Chewy"],
  "Napa Cabbage": ["Crunchy"],
  "Natural Yoghurt": ["Smooth"],
  "New Potatoes": ["Soft"],
  "Noodles": ["Chewy"],
  "Nutella": ["Smooth", "Sticky"],
  "Nutmeg": ["Grainy"],
  "Oatmeal": ["Grainy"],
  "Oats": ["Grainy"],
  "Oil": ["Smooth"],
  "Olive Oil": ["Smooth"],
  "Onion": ["Crunchy"],
  "Onion Salt": ["Grainy"],
  "Onions": ["Crunchy"],
  "Orange": ["Soft"],
  "Orange Blossom Water": ["Smooth"],
  "Orange Juice": ["Smooth"],
  "Orange Zest": ["Grainy"],
  "Oregano": ["Grainy"],
  "Oreo Cream Biscuits": ["Crunchy"],
  "Oxtail": ["Chewy"],
  "Oyster Mushrooms": ["Soft"],
  "Oyster Sauce": ["Smooth", "Sticky"],
  "Oysters": ["Slimy"],
  "Paccheri Pasta": ["Chewy"],
  "Padron peppers": ["Crunchy"],
  "Paella Rice": ["Grainy"],
  "Pak Choi": ["Crunchy"],
  "Palm Sugar": ["Grainy"],
  "Panang Curry Paste": ["Smooth"],
  "Paneer": ["Soft"],
  "Papelon": ["Grainy"],
  "Pappardelle Pasta": ["Chewy"],
  "Paprika": ["Grainy"],
  "Parma Ham": ["Chewy"],
  "Parmesan": ["Grainy"],
  "Parmesan Cheese": ["Grainy"],
  "Parmigiano-reggiano": ["Grainy"],
  "Parsley": ["Soft"],
  "Passata": ["Smooth"],
  "Passion Fruit Pulp": ["Smooth"],
  "Peach Juice": ["Smooth"],
  "Peaches": ["Soft"],
  "Peanut Brittle": ["Crunchy"],
  "Peanut Butter": ["Smooth", "Sticky"],
  "Peanut Cookies": ["Crunchy"],
  "Peanut Oil": ["Smooth"],
  "Peanuts": ["Crunchy"],
  "Pears": ["Soft"],
  "Peas": ["Soft"],
  "Pecan Nuts": ["Crunchy"],
  "Pecorino": ["Grainy"],
  "Penne Pasta": ["Chewy"],
  "Penne Rigate": ["Chewy"],
  "Pepper": ["Grainy"],
  "Peppercorns": ["Crunchy", "Grainy"],
  "Persian Cucumber": ["Crunchy"],
  "Petit Pois": ["Soft"],
  "Phyllo Dough": ["Flaky"],
  "Pickle Juice": ["Smooth"],
  "Pico De Gallo Sauce": ["Lumpy"],
  "Pilchards": ["Flaky"],
  "Pine Nuts": ["Crunchy"],
  "Pineapple Chunks": ["Soft"],
  "Pineapple Juice": ["Smooth"],
  "Pink Food Colouring": ["Smooth"],
  "Pinto Beans": ["Soft"],
  "Pistachio": ["Crunchy"],
  "Pistachio Paste": ["Smooth", "Sticky"],
  "Pita Bread": ["Soft", "Chewy"],
  "Pitted Black Olives": ["Chewy"],
  "Pitted Dates": ["Chewy", "Sticky"],
  "Plain Chocolate": ["Crunchy"],
  "Plain Flour": ["Grainy"],
  "Plum Jam": ["Smooth", "Sticky"],
  "Plum Sauce": ["Smooth", "Sticky"],
  "Plum Tomatoes": ["Soft"],
  "Polish Kabanos": ["Chewy"],
  "Polish Sausage": ["Chewy"],
  "Pomegranate": ["Crunchy"],
  "Pomegranate Molasses": ["Smooth", "Sticky"],
  "Poppy Seeds": ["Grainy"],
  "Pork": ["Chewy"],
  "Pork Back Ribs": ["Chewy"],
  "Pork belly slices": ["Chewy"],
  "Pork Chops": ["Chewy"],
  "Pork knuckle": ["Chewy"],
  "Pork Shoulder": ["Chewy"],
  "Pork Shoulder Steaks": ["Chewy"],
  "Pork Tenderloin": ["Chewy"],
  "Porridge oats": ["Grainy"],
  "Potato Starch": ["Grainy"],
  "Potatoe Buns": ["Soft"],
  "Potatoes": ["Soft"],
  "Powdered Sugar": ["Grainy"],
  "Prawns": ["Chewy"],
  "Pre-fried Tequeños": ["Crispy", "Chewy"],
  "Pretzels": ["Crunchy"],
  "Prosciutto": ["Chewy"],
  "Prunes": ["Chewy"],
  "Puff Pastry": ["Flaky"],
  "Pul Biber": ["Grainy"],
  "Pumpkin": ["Soft"],
  "Purple Sprouting Broccoli": ["Crunchy"],
  "Quinoa": ["Grainy"],
  "Radish": ["Crunchy"],
  "Rainbow Trout": ["Flaky"],
  "Raisins": ["Chewy"],
  "Rapeseed Oil": ["Smooth"],
  "Ras el hanout": ["Grainy"],
  "Raspberries": ["Soft"],
  "Raspberry Jam": ["Smooth", "Sticky"],
  "Raw Frozen Prawns": ["Chewy"],
  "Raw King Prawns": ["Chewy"],
  "Raw tiger prawns": ["Chewy"],
  "Raw Vegetables": ["Crunchy"],
  "Ready rolled shortcrust pastry": ["Flaky"],
  "Red Cabbage": ["Crunchy"],
  "Red Chilli": ["Crunchy"],
  "Red Chilli Flakes": ["Grainy"],
  "Red Chilli Powder": ["Grainy"],
  "Red Food Colouring": ["Smooth"],
  "Red Onions": ["Crunchy"],
  "Red Pepper": ["Crunchy"],
  "Red Pepper Flakes": ["Grainy"],
  "Red Pepper Paste": ["Smooth"],
  "Red Potatoes": ["Soft"],
  "Red Snapper": ["Flaky"],
  "Red Wine": ["Smooth"],
  "Red Wine Jelly": ["Smooth", "Sticky"],
  "Red Wine Vinegar": ["Smooth"],
  "Redcurrants": ["Soft"],
  "Refried Beans": ["Smooth", "Mushy"],
  "Rhubarb": ["Crunchy"],
  "Rice": ["Grainy"],
  "Rice Flour Pancakes": ["Chewy"],
  "Rice Krispies": ["Crunchy"],
  "Rice Noodles": ["Chewy"],
  "Rice Paper Sheets": ["Chewy"],
  "Rice Stick Noodles": ["Chewy"],
  "Rice Vermicelli": ["Chewy"],
  "Rice Vinegar": ["Smooth"],
  "Rice wine": ["Smooth"],
  "Ricotta": ["Soft", "Lumpy"],
  "Rigatoni": ["Chewy"],
  "Roasted Peanut": ["Crunchy"],
  "Roasted pepper": ["Soft"],
  "Roasted Vegetables": ["Soft"],
  "Rocket": ["Chewy"],
  "Rolled Oats": ["Grainy"],
  "Romano Pepper": ["Crunchy"],
  "Rose water": ["Smooth"],
  "Rosemary": ["Chewy"],
  "Rum": ["Smooth"],
  "Runner Beans": ["Crunchy"],
  "Russet Potato": ["Soft"],
  "Rye": ["Grainy"],
  "Rye Bread": ["Soft"],
  "Saffron": ["Grainy"],
  "Sage": ["Soft"],
  "Sake": ["Smooth"],
  "Salmon": ["Flaky"],
  "Salsa": ["Lumpy"],
  "Salt": ["Grainy"],
  "Salt Cod": ["Chewy"],
  "Salted Butter": ["Soft", "Smooth"],
  "Sardines": ["Flaky"],
  "Saskatoon Berries": ["Soft"],
  "Sauerkraut": ["Crunchy"],
  "Sausages": ["Chewy"],
  "Savoy Cabbage": ["Crunchy"],
  "Sazon": ["Grainy"],
  "Scallions": ["Crunchy"],
  "Scotch Bonnet": ["Crunchy"],
  "Sea Bass": ["Flaky"],
  "Sea Bass Fillets": ["Flaky"],
  "Sea Salt": ["Grainy"],
  "Seafood stock": ["Smooth"],
  "Seasoned Rice Vinegar": ["Smooth"],
  "Seasoning": ["Grainy"],
  "Self-raising Flour": ["Grainy"],
  "Semi-skimmed Milk": ["Smooth"],
  "Semolina": ["Grainy"],
  "Semolina Flour": ["Grainy"],
  "Serrano Ham": ["Chewy"],
  "Sesame Seed": ["Crunchy"],
  "Sesame Seed Burger Buns": ["Soft"],
  "Sesame Seed Oil": ["Smooth"],
  "Sevaiiya": ["Chewy"],
  "Shallots": ["Crunchy"],
  "Shaoxing Wine": ["Smooth"],
  "Shelled Hazelnuts": ["Crunchy"],
  "Sherry": ["Smooth"],
  "Sherry vinegar": ["Smooth"],
  "Shiitake Mushrooms": ["Soft"],
  "Shortcrust Pastry": ["Flaky"],
  "Shortening": ["Soft", "Smooth"],
  "Shredded Coconut": ["Flaky", "Chewy"],
  "Shredded Meat": ["Chewy"],
  "Shredded Mexican Cheese": ["Soft"],
  "Shredded Monterey Jack Cheese": ["Soft"],
  "Shrimp": ["Chewy"],
  "Shrimp Paste": ["Smooth", "Sticky"],
  "Shrimp Stock": ["Smooth"],
  "Sichuan Pepper": ["Grainy"],
  "Silken Tofu": ["Soft", "Smooth"],
  "Single Cream": ["Smooth"],
  "Sirloin steak": ["Chewy"],
  "Sirloin Steak tips": ["Chewy"],
  "Skirty Steak": ["Chewy"],
  "Small Potatoes": ["Soft"],
  "Smoked Haddock": ["Flaky"],
  "Smoked Paprika": ["Grainy"],
  "Smoked Salmon": ["Flaky"],
  "Smoked Turkey Neck": ["Chewy"],
  "Smoky Aïoli": ["Smooth"],
  "Smoky Paprika": ["Grainy"],
  "Snapper Fish": ["Flaky"],
  "Snow Peas": ["Crunchy"],
  "Soda Water": ["Smooth"],
  "Sour Cream": ["Smooth"],
  "Soured cream and chive dip": ["Smooth"],
  "Soy Sauce": ["Smooth"],
  "Soya Bean": ["Crunchy"],
  "Soya Milk": ["Smooth"],
  "Spaghetti": ["Chewy"],
  "Speculaas Spice Mix": ["Grainy"],
  "Spinach": ["Soft"],
  "Split Peas": ["Grainy"],
  "Spring Onions": ["Crunchy"],
  "Squash": ["Soft"],
  "Squid": ["Rubbery"],
  "Sriracha": ["Smooth"],
  "Stale bread": ["Soft"],
  "Star Anise": ["Crunchy"],
  "Starch": ["Grainy"],
  "Stilton Cheese": ["Lumpy", "Soft"],
  "Stir-fry Vegetables": ["Crunchy"],
  "Stoned Dates": ["Chewy", "Sticky"],
  "Stout": ["Smooth"],
  "Strawberries": ["Soft"],
  "Streaky Bacon": ["Chewy"],
  "Strong white bread flour": ["Grainy"],
  "Strong White Flour": ["Grainy"],
  "Strong Wholemeal Flour": ["Grainy"],
  "Suet": ["Soft"],
  "Sugar": ["Grainy"],
  "Sugar Snap Peas": ["Crunchy"],
  "Sugar Syrup": ["Smooth", "Sticky"],
  "Sultanas": ["Chewy"],
  "Sumac": ["Grainy"],
  "Sun-Dried Tomatoes": ["Chewy"],
  "Sunflower Oil": ["Smooth"],
  "Sushi Rice": ["Grainy"],
  "Swede": ["Crunchy"],
  "sweet chilli sauce": ["Smooth", "Sticky"],
  "Sweet Peppadew Peppers": ["Soft"],
  "Sweet Potatoes": ["Soft"],
  "Sweet Red Peppers": ["Crunchy"],
  "Sweet Sherry": ["Smooth"],
  "sweet smoked paprika": ["Grainy"],
  "Sweetcorn": ["Crunchy"],
  "Sweetened Condensed Milk": ["Smooth", "Sticky"],
  "Szechuan Peppercorns": ["Crunchy", "Grainy"],
  "Tabasco Sauce": ["Smooth"],
  "Tagliatelle": ["Chewy"],
  "Tahini": ["Smooth"],
  "Tahini Paste": ["Smooth"],
  "Tamarind Ball": ["Chewy", "Sticky"],
  "Tamarind Paste": ["Smooth", "Sticky"],
  "Tamarind Pulp": ["Sticky"],
  "Tarragon Leaves": ["Soft"],
  "Tempeh": ["Chewy"],
  "Thai Chilli Jam": ["Sticky", "Lumpy"],
  "Thai Fish Sauce": ["Smooth"],
  "Thai Green Curry Paste": ["Smooth"],
  "Thai Red Curry Paste": ["Smooth"],
  "Thyme": ["Soft"],
  "Tiger Prawns": ["Chewy"],
  "Tinned Tomatos": ["Soft", "Smooth"],
  "Toast": ["Crunchy"],
  "Toffee Popcorn": ["Crunchy", "Sticky"],
  "Tofu": ["Soft"],
  "Tomato": ["Soft"],
  "Tomato Ketchup": ["Smooth", "Sticky"],
  "Tomato Puree": ["Smooth"],
  "Tomato Sauce": ["Smooth"],
  "Tomatoes": ["Soft"],
  "Toor Dal": ["Grainy"],
  "Tortillas": ["Chewy"],
  "Treacle": ["Smooth", "Sticky"],
  "Tripe": ["Chewy", "Rubbery"],
  "Trout": ["Flaky"],
  "Truffle Oil": ["Smooth"],
  "Tuna": ["Chewy"],
  "Turkey": ["Chewy"],
  "Turkey Ham": ["Chewy"],
  "Turkey Mince": ["Chewy"],
  "Turkey Neck": ["Chewy"],
  "Turkish Delight": ["Chewy", "Sticky"],
  "Turmeric": ["Grainy"],
  "Turmeric Powder": ["Grainy"],
  "Turnips": ["Crunchy"],
  "Udon Noodles": ["Chewy"],
  "Unflavoured Gelatin": ["Chewy"],
  "Unsalted Beef Stock": ["Smooth"],
  "Unsalted Butter": ["Soft", "Smooth"],
  "Unsalted Pistachio": ["Crunchy"],
  "Unsweetened Cocoa": ["Grainy"],
  "Unsweetened Coconut Milk": ["Smooth"],
  "Unwaxed Lemon": ["Soft"],
  "Unwaxed Lime": ["Soft"],
  "Vanilla": ["Smooth"],
  "Vanilla Bean Paste": ["Smooth", "Sticky"],
  "Vanilla Custard": ["Smooth"],
  "Vanilla Extract": ["Smooth"],
  "vanilla pod": ["Chewy"],
  "vanilla sugar": ["Grainy"],
  "västerbottensost cheese": ["Chewy"],
  "Veal": ["Chewy"],
  "Vegan Butter": ["Soft", "Smooth"],
  "Vegan White Wine Vinegar": ["Smooth"],
  "Vegetable Oil": ["Smooth"],
  "Vegetable Shortening": ["Soft", "Smooth"],
  "Vegetable Stock": ["Smooth"],
  "Vegetable Stock Cube": ["Grainy"],
  "Vermicelli Pasta": ["Chewy"],
  "Vermicelli Rice Noodles": ["Chewy"],
  "Vinaigrette Dressing": ["Smooth"],
  "Vine Leaves": ["Chewy"],
  "Vine Tomatoes": ["Soft"],
  "Vinegar": ["Smooth"],
  "Walnuts": ["Crunchy"],
  "Warm Water": ["Smooth"],
  "Water": ["Smooth"],
  "Water Chestnut": ["Crunchy"],
  "Whipping Cream": ["Smooth"],
  "White Asparagus": ["Crunchy"],
  "White bread": ["Soft"],
  "White Bread Mix": ["Grainy"],
  "White Cabbage": ["Crunchy"],
  "White Chocolate": ["Crunchy"],
  "White Chocolate Chips": ["Crunchy"],
  "White Cornmeal": ["Grainy"],
  "White Fish": ["Flaky"],
  "White Fish Fillets": ["Flaky"],
  "White Flour": ["Grainy"],
  "White Masarepa": ["Grainy"],
  "White Sauerkraut": ["Crunchy"],
  "White Vinegar": ["Smooth"],
  "White Wine": ["Smooth"],
  "White Wine Vinegar": ["Smooth"],
  "White Yam": ["Crunchy"],
  "Whole black peppercorns": ["Crunchy", "Grainy"],
  "Whole Milk": ["Smooth"],
  "Whole Wheat": ["Grainy"],
  "Wholegrain Bread": ["Soft"],
  "Wholegrain Mustard": ["Grainy", "Lumpy"],
  "Wild Garlic Leaves": ["Soft"],
  "Wild Mushrooms": ["Soft"],
  "Wonton Skin": ["Chewy"],
  "Wood Ear Mushrooms": ["Chewy"],
  "Worcestershire Sauce": ["Smooth"],
  "Yautia": ["Crunchy"],
  "Yeast": ["Grainy"],
  "Yellow Food Colouring": ["Smooth"],
  "Yellow Masarepa": ["Grainy"],
  "Yellow Onion": ["Crunchy"],
  "Yellow Pepper": ["Crunchy"],
  "Yellow Split Peas": ["Grainy"],
  "Yogurt": ["Smooth"],
  "Yukon Gold Potatoes": ["Soft"],
  "Zucchini": ["Soft"],
};
